import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { promises as fs } from 'fs'
import path from 'path'
import PokemonComponent from '../components/PokemonComponent'
import { getPokeTypes } from '../modules'
import { DamageMap } from '../modules/pokeApiTypes';
import { GetStaticProps } from 'next'
import { Suspense } from 'react'

interface Props {
  types: string[];
  damages: DamageMap;
};

export default function Home(props: Props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>PokeApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-7xl mb-8'>
          This is <span className='text-red-700'>Poke</span><span className='text-gray-200'>App</span>!
        </h1>

        <nav className='flex gap-x-12'>
          <Link href='./' className='border-4 border-yellow-500 px-4 py-2 w-48 text-center text-2xl text-yellow-200 hover:underline'> Home </Link>
          <Link href='./team-builder' className='border-4 border-yellow-500 px-4 py-2 w-48 text-center text-2xl text-yellow-200 hover:underline'> Team Builder </Link>
        </nav>
        
        <PokemonComponent {...props} />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const dataPath = path.join(process.cwd(), 'data/pokemonTypeData.json');
  const data = await fs.readFile(dataPath, 'utf-8')

  const typeData = JSON.parse(data);

  return {
    props: {
      types: typeData.types,
      damages: typeData.damages,
    }
  };
}

// export const getStaticProps: GetStaticProps<Props> = async () => {
//   const res = await getPokeTypes();
//   console.log(res);

//   return {
//     props: {
//       types: res.types,
//       damages: res.damages,
//     }
//   };
// }
