import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { NavMenu, Loading } from '../components'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>PokeApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavMenu />

      <main className='h-full flex flex-col items-center justify-center'>
        <h1 className='text-7xl mb-4'>
          This is <span className='text-red-700'>Poke</span><span className='text-gray-200'>App</span>!
        </h1>

        <div>Under Construction</div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
