import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react";
import { getRandomTeam } from '../modules';
import { Pokemon } from '../modules/pokeApiTypes';
import { Loading, NavMenu } from '../components';

function capitalize(str: string): string {
  const transformed = str[0].toUpperCase() + str.slice(1);
  return transformed;
}

export default function TeamBuilder() {
  const [team, setTeam] = useState<Pokemon[]>();
  const [debounce, setDebounce] = useState(false);
  const [loading, setLoading] = useState(false);

  const generateTeam = () => {
    if(debounce) {
      console.log('waiting for debounce)');
      return;
    }
    setLoading(true);
    getRandomTeam()
      .then(data => {
        setTeam(data);
        setLoading(false);
      });
    setDebounce(true);
    setTimeout(() => {
      setDebounce(false)
      console.log('debounce reset');
    }, 5000);
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavMenu />

      <main className='h-full flex flex-col items-center justify-center'>
        <h1 className='text-7xl mb-4'>
          This is <span className='text-red-700'>Poke</span><span className='text-gray-200'>App</span>!
        </h1>
        
        <div className="my-auto flex flex-col items-center">
          <div className="grid grid-cols-3 gap-8 mb-4">
            {team ? team.map(pokemon => 
              <div key={pokemon.id}>
                <h3 className="text-center font-bold text-lg">
                  {capitalize(pokemon.name)}
                </h3> 
                <img 
                  src={pokemon.sprites.front} 
                  width='200' height='200' 
                  alt={capitalize(pokemon.name)} 
                  style={{imageRendering: 'pixelated'}} 
                  className='border-2 p-4 border-zinc-200 bg-gray-900'
                />
              </div>
            ) : loading ? <Loading/> : null}
          </div>

          <button className="border-1 rounded-md w-48 bg-gray-300 font-semibold text-lg text-gray-900" 
            onClick={generateTeam} 
          >
            GENERATE A TEAM
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}