import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useState } from "react";
import { getRandomTeam } from '../modules';
import { Pokemon } from '../modules/pokeApiTypes';

function capitalize(str: string): string {
  const transformed = str[0].toUpperCase() + str.slice(1);
  // console.log("🚀 ~ file: team-builder.tsx ~ line 11 ~ capitalize ~ transformed", transformed);

  return transformed;
}

export default function TeamBuilder() {
  const [team, setTeam] = useState<Pokemon[]>();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>PokeApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-7xl mb-8'>
          This is <span className='text-red-700'>Poke</span><span className='text-gray-200'>App</span>!
        </h1>

        <nav className='mb-6 flex gap-x-8'>
          <Link href='./' className='text-2xl text-yellow-200 hover:underline'> Home </Link>
          <Link href='./team-builder' className='text-2xl text-yellow-200 hover:underline'> Team Builder </Link>
        </nav>
        
        <div className="flex flex-col items-center">
          <div className="grid grid-cols-3 gap-8 mb-4">
            {team ? team.map(pokemon => 
              <div key={pokemon.id}>
                <h3 className="text-center font-bold text-lg">
                  {capitalize(pokemon.name)}
                </h3> 
                <img 
                  src={pokemon.sprites.front} 
                  width='200' height='200' 
                  alt={capitalize(pokemon.name)} 
                  style={{imageRendering: 'pixelated'}} 
                  className='border-2 p-4 border-zinc-200 bg-gray-900'
                />
              </div>
            ) : null}
          </div>
          <button className="border-1 rounded-md w-48 bg-gray-300 font-semibold text-lg text-gray-900" onClick={() => {
            getRandomTeam()
              .then(setTeam);
          }} >
            GENERATE A TEAM
          </button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}