import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { promises as fs } from 'fs'
import path from 'path'
import { NavMenu, TypeChart } from '../components'
import { DamageMap } from '../modules/pokeApiTypes';
import { GetStaticProps } from 'next'

interface Props {
  types: string[];
  damages: DamageMap;
};

export default function TypeData(props: Props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>PokeApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavMenu />

      <main className='h-full flex flex-col items-center justify-center'>
        <h1 className='text-7xl mb-4'>
          This is <span className='text-red-700'>Poke</span><span className='text-gray-200'>App</span>!
        </h1>
        <div className='my-auto'>
          <TypeChart {...props} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const dataPath = path.join(process.cwd(), 'data/pokemonTypeData.json');
  const data = await fs.readFile(dataPath, 'utf-8');
  const typeData = JSON.parse(data);

  // console.log(typeData);

  return {
    props: {
      types: typeData.types,
      damages: typeData.damages,
    }
  };
}